### PR TITLE
Exception handling and CLI done...Issue #7 and #9...Please check...

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Krythz43 — CHANGES_REQUESTED** [review]
Hey @sen-session! Thanks for the PR.
You might have noticed the main aim of the Javascript version of the program is to convert the python interface into a web app so that it would be much easier to use.

As of the Python version, it's for easier understanding of the logic through which it works and for easier modifications. Am sorry for not mentioning this earlier. #9 is actually for JS version. So here is what you could do for now:
- Reset to the previous head.
- Commit the changes you included for #7 
- Requests library is chill, so lets not fix anything that ain't broke.

I am really sorry, because I understand that you might have spent a lot of time on this. But fixing #9 here just makes the code messier.

**Comment by sen-session** [comment]
But command line arguments are included... And also requests cannot handle
changes in proxy, urllib auto detects them.... Thus, the changes....

**Review by Krythz43 — CHANGES_REQUESTED** [review]
Yeah but exception handling in python version destroys the code readability. As I said, the main focus of the python code is to implement the logic.  So could you please remove the exceptions handled part? Also as I said earlier, that was intended for the javascript version. Its always good practice to get yourselves assigned onto an issue before you start working on it.

**Comment by sen-session** [comment]
Hello! I am the same Aritra Sen ...I have just learned to pull fork and push...and this is another account...the previous one is deleted....can you please assign me the task of command line arguments...?

**Comment by sen-session** [comment]
I will also remove the exception handling part, if you say to....

**Comment by sen-session** [comment]
However,not much of exception handling is done and main part is the argparse part, saving of details of multiple users,  and of course, auto-handling of proxies....

**Pull request closed without merging**
